language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"


# Command to install dependencies.
install:
  - pip install -r requirements/dev.txt

# Build script (If successfully built - no errors)
script:
  - pytest
  - pylint search_engine_parser --exit-zero
  - ./scripts/pre_deploy_test.sh

after_success:
  - python setup.py --version

deploy:
  provider: pypi
  user: "deven96"
  password: $PYPI_PASSWORD
  condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+
  skip_existing: true
  on:
    branch: master

after_deploy:
  - ./scripts/post_deploy_test.sh
  # - ./scripts/docs.sh

notifications:
# slack channel notification
    slack: bisoncorps:urrq42VfAo4zJP2r6lH2dU8Y
